import pandas as pd
import numpy
from sodapy import Socrata
from config_parser import get_param
from db_utils import create_mysql_connection, read_table_to_df


def create_dims(source_data):
    
    attributes_list = get_param('DIM','list')

    created_dims = []

    for attribute in attributes_list:
        created_dims.append(dim_by_column(source_data, attribute))

    if len(attributes_list) != len(created_dims):
        raise Exception("ERROR: there were some dimensions that couldn't been created - \n \
            Dimension List: "+ ','.join(attributes_list)+ "\nCreated Dimensions" \
                + ','.join(create_dims))
    else:
        return created_dims     


def dim_by_column(df, column_name):
    #This function returns a pandas dataframe with a sequential autogenerated Id and the attribute to be dimensioned
    df[column_name].drop_duplicates().sort_values().reset_index(drop=True).dropna()
    df["Id"] = df.index + 1
    final_df = df["Id",column_name]
    load_dimension(column_name, final_df)
    

def load_dimension(dimension_name, df):
    db_connection = create_mysql_connection()
    df.to_sql(name=dimension_name, con=db_connection, if_exists='replace')

def replace_attr_id(df, dim):
    df_dim = read_table_to_df(dim)

    #fact left_join dim replace attr with id
    replaced_df = ''
    return replaced_df


def load_fact(df):
    
    dim_list = get_param('DIM','list')

    for dim in dim_list:
        df_result = replace_attr_id(df, dim)
    
    return df_result


